### ISSUE TITLE
D-Day British

### ISSUE THREAD

**Issue by OneUpTonUp** [BSData/flamesofwar#11]
Would someone mind adding the new D-Day British (V4) forces to BattleScribe? I have no experience with GitHub or programming or I'd offer to contribute...

**Comment by Tilioch** [comment]
I'd like to help you with this, but I don't have the book yet. It will be added as soon as I can get it and some time to implement it.

**Comment by OneUpTonUp** [comment]
I've got the book - I can send pictures of whatever you need, just let me
know what and where to send them

**Comment by Tilioch** [comment]
That would be great, if I could get images of the formations, stats and army composition, and if possible, in some order so that it's possible to tell what page is in what order.
You could send it to battlescribe@bernestedt.se
And I'll get on it as soon as I can. It usually takes me a couple of weeks to get the time to get a first version out.
