### ISSUE TITLE
Bulge: America UX feedback

### ISSUE THREAD

**Issue by Willus8888** [BSData/flamesofwar#42]
Hi All,

Let me know feedback on the layout of Bulge: America.
I was trying to build it so it as represetitive to the material as well as being easy to use.
My initial attempt at this is in with Bagration: Soviet.

I have added Command Cards are if you were playing, however some modifications need to be done ont he Units themselves to apply points etc.

Have a play around and let me know what you think.

**Comment by mdcooledge** [comment]
Hey @Willus8888 

I like the way the Bulge: American layout looks and how the command cards actually affect the list building. I was looking at trying my hand at this. Is there a good starting point. I only play Germans and would love to get some of their new Bulge releases into the Battlescribe app. Is there any way I can help. I have downloaded the editor and github repository to start looking at how you setup the Bulge: Americans. Looks like a lot of work but keep up the good work. I might try my hand at this and see if I can develop anything decent. Let me know your thoughts on this.

**Comment by mdcooledge** [comment]
@Willus8888 I ended up building out the Bulge: Germans more like others had done. I like being able to see all the options I have in a formation instead of clicking on each numbered combat unit, at least when it comes to iOS. That being said take my opinion as a grain of salt. I am just glad you are willing to develop the data file. Edit the way you think best. Thanks again. Closing out the issue.
