### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by Tilioch** [BSData/flamesofwar#5]
I'd like to join so that I can get some files in for v4

**Comment by amis92** [comment]
Hello, @Tilioch . Please accept the invitation in the email or on the [webpage][invitation]. Welcome aboard!

Don't forget to read through [wiki][], there are some useful guides, especially [Data Author Guide][guide].

Also, join the data author community over at discord!

[![Chat on Discord](https://img.shields.io/discord/558412685981777922.svg?logo=discord&style=popout-square)](https://discord.gg/KqPVhds)

Cheers!

[invitation]: https://github.com/BSData/flamesofwar/invitations
[wiki]: https://github.com/BSData/catalogue-development/wiki
[guide]: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide

PS I think since there are no other maintainers, you'll be on your own :)
